#!/usr/bin/env bash
# Configures an Ubuntu server with custom IP resolutions
cp /etc/hosts /etc/hosts.bak
awk '{if($2=="localhost") $1="127.0.0.2"; print}' /etc/hosts.bak > /etc/hosts
sed -i '/facebook.com/d' /etc/hosts.bak
echo "8.8.8.8 facebook.com" >> /etc/hosts
